version: '3.8'

services:
  flask_1:
    build: ./flask
    container_name: flask_1
    environment:
      - APP_NAME=RecipeFinder
    ports:
      - "50100:50100"

  flask_2:
    build: ./flask
    container_name: flask_2
    ports:
      - "50101:50100"

  flask_3:
    build: ./flask
    container_name: flask_3
    ports:
      - "50102:50100"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - flask_1
      - flask_2
      - flask_3
