name: Python Linting

on: [push, pull_request]

jobs: 
  lint: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 
      uses: actions/setup-python@v5 
      with: 
        python-version: '3.8' 

    - name: Install Flake8 
      run: pip install flake8

    # some code doesn't work well when splitted into multiple lines
    # reassign max length to 110
    - name: Run Flake8 
      run: flake8 --max-line-length=110 flask