name: CI/CD Pipeline - Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPOONACULAR_API_1: ${{ secrets.SPOONACULAR_API_1 }}
      SPOONACULAR_API_2: ${{ secrets.SPOONACULAR_API_2 }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.8'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies 
      run: pip install -r requirements.txt 
      
    - name: Run tests
      run: pytest
